TEXFILES=main.tex

pdflatex:: $(TEXFILES)
	pdflatex main

lualatex:: $(TEXFILES)
	lualatex main

clean:
	rm -f main.pdf main.aux main.log main.out main.run.xml main.bcf main.fdb_latexmk main.fls main.dvi main.output main.abstract main.meta



