METACAPTURE_FILES = metacapture.sty metacapture-doc.tex metacapture-doc.pdf metacapture-doc.bib metacapture-sample.tex README.md

metacapture.tar.gz: $(METACAPTURE_FILES)
	ctanify --notds --pkgname=metacapture $(METACAPTURE_FILES)

