name: test of iacrcc LaTeX class.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  latex_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install texlive
      uses: teatimeguest/setup-texlive-action@v2
      with:
        packages: >-
          scheme-basic
          filehook
          currfile
          expl3
          xkeyval
          etoolbox
          xstring
          iftex
          luatex85
          fontenc
          fontspec
          pdfmanagement-testphase
          hyperref
          totpages
          geometry
          afterpage
          sectsty
          pgfkeys
          xpatch
          alphalph
          tokcycle
          listofitems
          fancyhdr
          graphicx
          csquotes
          biblatex
          doclicense
          fancyvrb
          amsthm
          mathtools
          floatrow
          caption
          float
          lineno
          microtype
          lipsum
          latexmk
          xifthen
          ccicons
          verbatim
          kvoptions
          ragged2e
          ifmtarg
    - name: Check `tlmgr` version
      run: tlmgr --version
    - name: Update all packages
      run: tlmgr update --all
    - name: Install dependencies
      working-directory: iacrcc/tests
      run: |
        python -m pip install --upgrade pip
        pip install pytest pdfplumber python-xmp-toolkit nameparser xmp pylatexenc
    - name: Test for compile_tests.py
      working-directory: iacrcc/tests
      run: |
        pytest -vv compile_tests.py
