name: test of iacrcc LaTeX class.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  latex_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install texlive
      uses: paolobrasolin/setup-texlive-action@v1
      with:
        profile-path: ${{ github.workspace }}/.github/texlive.profile
        packages-path: ${{ github.workspace }}/.github/texlive.packages
        run: | 
         tlmgr --version
         tlmgr update --all
    - name: Install dependencies
      working-directory: iacrcc/tests
      run: |
        python -m pip install --upgrade pip
        pip install pytest pdfplumber python-xmp-toolkit nameparser xmp pylatexenc pypdf
    - name: Test for compile_tests.py
      working-directory: iacrcc/tests
      run: |
        pytest -vv compile_tests.py
